remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Garden Buddy"
description: "This app will teach you when to plant, and help keep organized."
author:
  name: "Hana Dawson"

# Do not change the following line.
  copyright: true
